compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
enable_cpu_affinity: false
# gpu_ids: 0,1,2,3
# gpu_ids: 0,1
# gpu_ids: 1,0
gpu_ids: 1,2,3
# gpu_ids: 2,0
# gpu_ids: 0,3
# gpu_ids: 2,3
machine_rank: 0
main_training_function: main
# mixed_precision: 'fp16'
mixed_precision: 'no'
num_machines: 1
num_processes: 3
# num_processes: 3
rdzv_backend: static
same_network: true
main_process_port: 29500
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
